Refactor for author roles, and move meta to the _quarto.yml

diff --git a/babs/docs/makefile b/babs/docs/makefile
--- a/babs/docs/makefile
+++ b/babs/docs/makefile
@@ -4,9 +4,9 @@ include shared.mk
 .SILENT:
 
 specfiles = $(wildcard *.spec)
-samplesheet=$(wildcard samplesheet.csv)
+samplesheet=$(wildcard $(samplesheet_fname).csv)
 configs = $(wildcard *.config)
-experiment_table = $(wildcard experiment_table.csv)
+metadata = $(wildcard $(experiment_table).csv)
 
 .PHONY: build run clean
 
@@ -19,11 +19,11 @@ build: run
 # tmp.err is no longer present to allow future runs a clean state.
 
 
-run: $(specfiles) samplesheet.csv $(configs) $(experiment_table) ## Basic check that the contents of the docs folder conforms to requirements
+run: $(specfiles) check-samplesheet $(configs) $(metadata) ## Basic check that the contents of the docs folder conforms to requirements
 	$(GIT) commit -m "Adding files generated by a docs run" || echo "No docs files needed adding"
 	[ -n "$(specfiles)" ] || echo "No *.spec files in the docs directory" | tee -a tmp.err
 	[ -n "$(configs)" ] || echo "No *.config files in the docs directory" | tee -a tmp.err
-	[ -n "$(experiment_table)" ] || echo "No experiment_table.csv in the docs directory" | tee -a tmp.err
+	[ -n "$(metadata)" ] || echo "No $(experiment_table).csv in the docs directory" | tee -a tmp.err
 	[ -f tmp.err ] && mv tmp.err report.err || rm -f report.err
 	[ -f tmp.log ] && mv tmp.log report.log || touch report.log
 	[ ! -s report.err ]
@@ -33,31 +33,32 @@ $(specfiles) :
 	[[ -s "$@" ]] || { echo "$@ is empty" | tee -a tmp.err; }
 endif
 
-ifneq ($(samplesheet),)
-samplesheet.csv:
-	head -1 $@ | grep -q "^sample,fastq_1,fastq_2" || { echo "$@ has incorrect header" | tee -a tmp.err ;}
-	[ $(word 1,$(shell wc -l $@)) -ge 2 ] || { echo "@ has only one line" | tee -a tmp.err ;}
-else
 limsid=$(subst asf-,,$(subst lims-,,$(setting_Lims)))
 lab-sci=$(word 2,$(subst /projects/, ,$(dir $(setting_Path))))
-fqfiles=/nemo/stp/babs/inputs/sequencing/released/$(lab-sci)$(limsid)/primary_data/*/fastq/*_R1_001.fastq.gz
-samplesheet.csv : $(wildcard $(fqfiles))
-	if [ "$(words $(wildcard $(fqfiles)))" == "0" ] ;\
-	  then echo "Couldn't find fastq files in " $(fqfiles) | tee -a tmp.err;\
-	else echo "sample,fastq_1,fastq_2" > $@;\
-	  for r1 in $(fqfiles); do \
-	    echo -n $$(basename $$r1) | sed 's/_.*/,/' >> $@ ;\
-	    echo -n "$$r1," >> $@ ;\
-	    r2=`echo $$r1 | sed 's/_R1_/_R2_/'` ;\
-	    if [ -f "$$r2" ];\
-	      then echo $$r2 >> $@ ;\
-	      else echo "" >> $@ ;\
-	    fi ;\
-	  done ;\
-	fi
+fqfiles=$(wildcard /nemo/stp/babs/inputs/sequencing/released/$(lab-sci)$(limsid)/primary_data/*/fastq/*_R1_001.fastq.gz)
+
+.PHONY: check-samplesheet
+check-samplesheet: $(samplesheet_fname).csv
+	head -1 $< | grep -q "^sample,fastq_1,fastq_2" || { echo "$< has incorrect header" | tee -a tmp.err ;}
+	[ $(word 1,$(shell wc -l $<)) -ge 2 ] || { echo "$< has only one line" | tee -a tmp.err ;}
+
+
+$(samplesheet_fname).csv : $(fqfiles)
+ifeq ($(fqfiles),)
+	echo "Couldn't find fastq files in " $(fqfiles) | tee -a tmp.err
+else
+	echo "sample,fastq_1,fastq_2" > $@
+	for r1 in $(fqfiles); do \
+	  echo -n $$(basename $$r1) | sed 's/_.*/,/' >> $@ ;\
+	  echo -n "$$r1," >> $@ ;\
+	  r2=`echo $$r1 | sed 's/_R1_/_R2_/'` ;\
+	  if [ -f "$$r2" ];\
+	    then echo $$r2 >> $@ ;\
+	    else echo "" >> $@ ;\
+	  fi ;\
+	done
 	$(GIT) add $@
 endif
-
 
 
 ifneq ($(configs),)
@@ -66,13 +67,12 @@ $(configs) :
 endif
 
 
-ifneq ($(experiment_table),)
-$(experiment_table) :
+ifneq ($(metadata),)
+$(metadata) :
 	[[ -s "$@" ]] || { echo "$@ is empty" | tee -a tmp.err; }
-	head -1 $@ | grep -q "^ID" || { echo "experiment_table.csv does not start with an ID column" | tee -a tmp.err; }
-	head -1 $@ | grep -q "ID,sample_label" || { echo "experiment_table.csv does not have sample_label column after ID - the first unduplicated column after ID, or the ID itself will be used as a label" | tee -a tmp.log; }
+	head -1 $@ | grep -q "^$(metadata_id_column)" || { echo "$(metadata) does not start with a column named $(metadata_id_column)" | tee -a tmp.err; }
+	head -1 $@ | grep -q "$(metadata_id_column),sample_label" || echo "$(metadata) does not have sample_label column after $(metadata_id_column) - the first unduplicated column after $(metadata_id_column), or $(metadata_id_column) itself will be used as a label" | tee -a tmp.log
 endif
-
 
 clean:
 	rm -f report.err report.log
