feat: Make config-specific samplesheets

diff --git a/babs/docs/makefile b/babs/docs/makefile
--- a/babs/docs/makefile
+++ b/babs/docs/makefile
@@ -4,7 +4,7 @@ include shared.mk
 .SILENT:
 
 specfiles = $(wildcard *.spec)
-samplesheet=$(wildcard $(samplesheet_fname).csv)
+samplesheets=$(patsubst %.config,%.csv,$(configs))
 configs = $(wildcard *.config)
 metadata = $(wildcard $(experiment_table).csv)
 
@@ -21,7 +21,7 @@ endif
 # tmp.err is no longer present to allow future runs a clean state.
 
 
-run: $(specfiles) check-samplesheet $(configs) $(metadata) ## Basic check that the contents of the docs folder conforms to requirements
+run: $(specfiles) check-samplesheets $(configs) $(metadata) ## Basic check that the contents of the docs folder conforms to requirements
 	$(GIT) commit -m "Adding files generated by a docs run" || echo "No docs files needed adding"
 	[ -n "$(specfiles)" ] || echo "No *.spec files in the docs directory" | tee -a tmp.err
 	[ -n "$(configs)" ] || echo "No *.config files in the docs directory" | tee -a tmp.err
@@ -35,20 +35,21 @@ $(specfiles) :
 	[[ -s "$@" ]] || { echo "$@ is empty" | tee -a tmp.err; }
 endif
 
-fqfiles=$(wildcard $(fastq_wildcard))
 
-.PHONY: check-samplesheet
-check-samplesheet: $(samplesheet_fname).csv
-	head -1 $< | grep -q "^sample,fastq_1,fastq_2" || { echo "$< has incorrect header" | tee -a tmp.err ;}
-	[ $$(wc -l < $<) -ge 2 ] || { echo "$< has only one line" | tee -a tmp.err ;}
+.PHONY: check-samplesheets
+check-samplesheets: $(samplesheets)
+	for s in $(samplesheets); do \
+	  head -1 $$s | grep -q "^sample,fastq_1,fastq_2" || { echo "$$s has incorrect header" | tee -a tmp.err ;} ;\
+	  [ $$(wc -l < $$s) -ge 2 ] || { echo "$$s has only one line" | tee -a tmp.err ;} ;\
+	done
 
 
-$(samplesheet_fname).csv : $(fqfiles)
-ifeq ($(fqfiles),)
-	echo "Couldn't find fastq files in $(fastq_wildcard). Perhaps try setting fastq_wildcard, or change your answers file" | tee -a tmp.err
-else
-	echo "sample,fastq_1,fastq_2" > $@
-	for r1 in $(fqfiles); do \
+$(samplesheets) : %.csv : %.config
+	if [ -z "$(wildcard $($*.fastq_wildcard))" ]; then  \
+	  echo "Couldn't find fastq files in $(fastq_wildcard). Perhaps try setting fastq_wildcard, or change your answers file" | tee -a tmp.err ;\
+	  exit ;\
+	fi
+	for r1 in $(wildcard $($*.fastq_wildcard)); do \
 	  echo -n $$(basename $$r1) | sed 's/_.*/,/' >> $@ ;\
 	  echo -n "$$r1," >> $@ ;\
 	  r2=`echo $$r1 | sed 's/_R1_/_R2_/'` ;\
@@ -58,7 +59,6 @@ else
 	  fi ;\
 	done
 	$(GIT) add $@
-endif
 
 
 ifeq ($(configs),)
