chore: Tidy up makefile brackets and auto-gitting
Also, remove more of the legacy 'build' rubric

diff --git a/babs/differential/makefile b/babs/differential/makefile
--- a/babs/differential/makefile
+++ b/babs/differential/makefile
@@ -63,7 +63,7 @@ $(mk0): $(staging_dir)/.make-% : $(samplesheets) | $(staging_dir)
 
 ifeq (,$(filter $(excluded-targets),$(MAKECMDGOALS)))
 ifneq (,$(excluded-targets))
-include ${configs}
+include $(configs)
 endif
 endif
 
@@ -74,12 +74,12 @@ html_reports=$(strip $(foreach section,$(sections),$($(section)_htmls)))
 ifeq ($(SUBMIT),false)
     ifeq ($(CONTAINERED),false)
 ##     Being executed directly - no submission or containerisation
-.PHONY: run render pages scripts
+.PHONY: run pages scripts
 
-run: render  ## Create objects in `data` that store the results of applying each spec file, along with a versioned html report in `results`.  Requires 'make build' be done first.
 
 ## Render the qmds to html in one quarto call
-render: $(qmds)  $(staging_dir)/_quarto.yml $(staging_dir)/index.qmd $(samplesheets)| $(log_dir) data $(RESULTS_DIR)/$(VERSION) $(staging_dir)/R.bib $(genes_results)  ## Render the whole directory of generated qmds
+run: $(qmds) $(staging_dir)/_quarto.yml $(staging_dir)/index.qmd $(samplesheets)| $(log_dir) data $(RESULTS_DIR)/$(VERSION) $(staging_dir)/R.bib $(genes_results)  ## Create objects in `data` that store the results of applying each spec file, along with a versioned html report in `results`.
+	$(GIT) commit -m "Adding files generated by a differential run" || echo "No additional differential files needed adding"
 	sed  -i 's#^  contents: .*#  contents: [$(subst $(space),$(comma),$(patsubst $(staging_dir)/%,%,$(qmds)))]#' $(staging_dir)/index.qmd
 	$(QUARTO) render '$(staging_dir)' --output-dir $(RESULTS_DIR)/$(VERSION) --execute-dir $(CURDIR) $(call log,render)
 	cp -rT $(staging_dir)/$(RESULTS_DIR)/$(VERSION) $(RESULTS_DIR)/$(VERSION)
@@ -115,7 +115,7 @@ $(qmds) : $(staging_dir)/%$(TAG).qmd : $(staging_dir)/.params.yml $(source_dir)/
 	 --generated=$(staging_dir)/.params.yml > $@
 	sed -i -e 's#load_params("$(source_dir)/$(section)", extra=TRUE)#load_params("$(staging_dir)/$*$(TAG)")#' $@
 
-${staging_dir}/_quarto.yml: $(source_dir)/_quarto.yml $(qmds)
+$(staging_dir)/_quarto.yml: $(source_dir)/_quarto.yml $(qmds)
 	$(QUARTO) run $(source_dir)/typescript/sidebar.ts\
 	 --sections="$(subst $(space),$(comma),$(sections))"\
 	 --alignments="$(subst $(space),$(comma),$(alignments))"\
@@ -125,14 +125,13 @@ ${staging_dir}/_quarto.yml: $(source_dir)/_quarto.yml $(qmds)
 	 --staging=$(staging_dir)\
 	 --repo="$(repo)" > $@
 
-$(source_dir)/params.yml:
-	echo "" > $@
+
 
 $(staging_dir)/.params.yml:  project.mk
-	echo '{$(foreach p,$(param_names),$p: "${$p}"$(comma))}' > $@
+	echo '{$(foreach p,$(param_names),$p: "$($p)"$(comma))}' > $@
 
 
-${staging_dir}/index.qmd : $(source_dir)/index.qmd $(qmds)
+$(staging_dir)/index.qmd : $(source_dir)/index.qmd $(qmds)
 	sed  's#^  contents: .*#  contents: [$(subst $(space),$(comma),$(patsubst $(staging_dir)/%,%,$(qmds)))]#' $< > $@
 
 $(staging_dir)/R.bib: R.bib
@@ -147,27 +146,30 @@ renv.lock: resources/_dependencies.R $(wildcard pre.renv.lock)
 	  $(GIT) mv pre.renv.lock renv.lock || mv pre.renv.lock renv.lock;\
 	  $(R) -e 'library(renv); restore()' ;\
 	  $(R) -e 'library(renv); install(); snapshot()' ;\
-	  $(GIT) add renv.lock resources/_dependencies.R renv/activate.R .Rprofile renv/settings.json $(call log,renv,-a) ;\
-	  $(GIT) commit -m 'Renv initialised by pipeline\n\n' $(call log,renv,-a) ;\
-	  $(GIT) rev-parse "v0.0.1" >/dev/null 2>&1 || $(GIT) tag v0.0.1 $(call log,renv,-a); \
 	else \
 	  $(GIT) stash push -m "Pipeline stashed. Use 'git stash pop' to retrieve it" -- $@ $(call log,renv)
 	  $(R) -e 'library(renv); init(bioconductor=TRUE); snapshot()' ;\
-	fi	
+	fi
+	$(GIT) add $(source_dir) $(call log,renv,-a) 
+	$(GIT) add makefile shared.mk .Rprofile project.mk module.mk .gitignore .Rbuildignore $(call log,renv,-a) 
+	$(GIT) add renv.lock renv/settings.json renv/activate.R $(call log,renv,-a) 
+	$(GIT) commit -m 'Renv initialised by pipeline\n\n' || echo "No initialisation files need commiting" $(call log,renv,-a) 
+	$(GIT) rev-parse "v0.0.1" >/dev/null 2>&1 || $(GIT) tag v0.0.1 $(call log,renv,-a)
 
 resources/_dependencies.R: orgs=$(foreach align,$(alignments),$($(align).org.db))
 resources/_dependencies.R: $(patsubst %,%.config,$(alignments))
 	for o in $(orgs); do grep -F -q $$o $@ || echo "library($$o)" >> $@; done
 	touch $@
+	$(GIT) add $@
 
     else
 ##   being executed by container without slurm, so put what 'make' would normally execute in a temporary
 ##   shell script, and get container to call that script (so it naturally inherits all the command line
 ##   arguments etc)
-run render pages $(html_reports) scripts $(qmds) ${staging_dir}/_quarto.yml ${staging_dir}/index.qmd  ${staging_dir}/R.bib renv.lock: $(CONTAINER_IMAGE)
-	make -n -s $@ SUBMIT=false EXECUTOR=make > ${TMPSCRIPT}_bash 
-	$(CONTAINER) $(CONTAINER_FLAGS) $(CONTAINER_IMAGE) bash "${TMPSCRIPT}_bash" || { echo "${TMPSCRIPT}_bash failed." $(call log,container) ; exit 1; }
-	rm -f ${TMPSCRIPT}_bash
+run  pages $(html_reports) scripts $(qmds) $(staging_dir)/_quarto.yml $(staging_dir)/index.qmd  $(staging_dir)/R.bib renv.lock: $(CONTAINER_IMAGE)
+	make -n -s $@ SUBMIT=false EXECUTOR=make > $(TMPSCRIPT)_bash 
+	$(CONTAINER) $(CONTAINER_FLAGS) $(CONTAINER_IMAGE) bash "$(TMPSCRIPT)_bash" || { echo "$(TMPSCRIPT)_bash failed." $(call log,container) ; exit 1; }
+	rm -f $(TMPSCRIPT)_bash
     endif
 else
 ## being submitted. So generate a slurm script with the usual slurm
@@ -181,15 +183,15 @@ slurm-container-prefix=$(CONTAINER) $(CONTAINER_FLAGS) $(CONTAINER_IMAGE)
 slurm-container-prefix=
     endif
 #JFLAG= -j $(SLURM--cpus-per-task)# Haven't got parallel make working with quarto. race condition?
-run render pages $(html_reports) scripts $(qmds) ${staging_dir}/_quarto.yml ${staging_dir}/index.qmd ${staging_dir}/R.bib renv.lock: $(CONTAINER_IMAGE)
-	echo "$$slurm" > ${TMPSCRIPT}_slurm
-	make -n -s $@ SUBMIT=false EXECUTOR=make > ${TMPSCRIPT}_slurm.sh
-	echo "$(slurm-container-prefix) ${TMPSCRIPT}_slurm.sh" >> ${TMPSCRIPT}_slurm
-	echo 'r=$$?' >>  ${TMPSCRIPT}_slurm
-	echo '$(notification)' >> ${TMPSCRIPT}_slurm
-	$(make_rwx) ${TMPSCRIPT}_slurm
-	$(make_rwx) ${TMPSCRIPT}_slurm.sh
-	sbatch ${TMPSCRIPT}_slurm 
+run pages $(html_reports) scripts $(qmds) $(staging_dir)/_quarto.yml $(staging_dir)/index.qmd $(staging_dir)/R.bib renv.lock: $(CONTAINER_IMAGE)
+	echo "$$slurm" > $(TMPSCRIPT)_slurm
+	make -n -s $@ SUBMIT=false EXECUTOR=make > $(TMPSCRIPT)_slurm.sh
+	echo "$(slurm-container-prefix) $(TMPSCRIPT)_slurm.sh" >> $(TMPSCRIPT)_slurm
+	echo 'r=$$?' >>  $(TMPSCRIPT)_slurm
+	echo '$(notification)' >> $(TMPSCRIPT)_slurm
+	$(make_rwx) $(TMPSCRIPT)_slurm
+	$(make_rwx) $(TMPSCRIPT)_slurm.sh
+	sbatch $(TMPSCRIPT)_slurm 
 
 endif
 
@@ -204,9 +206,9 @@ geo/md5.txt:
 	ln -fn $(my_counts_dir)/$(alignment)/*.genes.results shortcuts/geo/
 	ln -fn $(RESULTS_DIR)/$(version)/$(alignment)/$(spec)/*.xlsx shortcuts/geo/
 	$(SQLITE) $(samples_db) 'select fastq_1 from fastqs  where config_file="$(alignment)";' | \
-	while read -r fq ; do cp ${fq} shortcuts/geo/ ; done
+	while read -r fq ; do cp $${fq} shortcuts/geo/ ; done
 	$(SQLITE) $(samples_db) 'select fastq_2 from fastqs  where config_file="$(alignment)";' | \
-	while read -r fq ; do cp ${fq} shortcuts/geo/ ; done
+	while read -r fq ; do cp $${fq} shortcuts/geo/ ; done
 	pushd shortcuts/geo; md5sum *.* > geo.md5.txt; popd
 
 .PHONY: publish
@@ -224,37 +226,36 @@ publish: $(pubdir) ## Copy results to final location. Either 'outputs' folder (d
 #### Bootstrap all relevant data from outside
 ################################################################
 
-build: $(configs)  ##  Copy the required nfcore count files into the `extdata` area, and get the spec files.
+build: run  ##  'build' is deprecated - `make run` is now sufficient.
 
-ifneq (${docs_dir},)
+ifneq ($(docs_dir),)
 $(docs_dir)/%:
-	$(MAKE) --no-print-directory -C ${docs_dir} $*
+	$(MAKE) --no-print-directory -C $(docs_dir) $*
 
 $(file.spec): % : $(docs_dir)/%
-	$(MAKE) --no-print-directory -C ${docs_dir} $*
+	$(MAKE) --no-print-directory -C $(docs_dir) $*
 	cp $< $@
 	$(GIT) add $@
 endif
 
-ifneq (${ingress_dir},)
+ifneq ($(ingress_dir),)
 $(ingress_dir)/%:
-	$(MAKE) --no-print-directory -C ${ingress_dir} $*
+	$(MAKE) --no-print-directory -C $(ingress_dir) $*
 
 $(my_metadata).csv: $(ingress_dir)/$(experiment_table).csv | $(dir $(my_metadata))
-	$(MAKE) --no-print-directory -C ${ingress_dir} $(experiment_table).csv
+	$(MAKE) --no-print-directory -C $(ingress_dir) $(experiment_table).csv
 	cp $< $@
 	$(GIT) add $@
 endif
 
 
-ifneq (${nfcore_dir},)
+ifneq ($(nfcore_dir),)
 $(nfcore_dir)/%:
-	$(MAKE)  --no-print-directory -C ${nfcore_dir} $*
+	$(MAKE)  --no-print-directory -C $(nfcore_dir) $*
 
-$(samplesheets) : $(my_metadata)_%.csv : $(nfcore_dir)/samplesheet_%.csv ${samples_db} $(my_metadata).csv
+$(samplesheets) : $(my_metadata)_%.csv : $(nfcore_dir)/samplesheet_%.csv $(samples_db) $(my_metadata).csv
 	$(SQLITE) -header -csv  $(samples_db) --cmd '.import --csv --schema temp $(my_metadata).csv metadata' 'SELECT metadata.* FROM metadata INNER JOIN (SELECT * FROM "fastq_$*" GROUP BY $(samplesheet_id_column)) AS nfcore on metadata.$(metadata_id_column)=nfcore.$(samplesheet_id_column);' > $@
 	$(GIT) add $@
-	$(GIT) commit -m "Add the dependencies for $*" || true
 
 $(samples_db): $(nfcore_dir)/$(samples_db) | $(file.spec) $(staging_dir)
 	cp $< $@ || echo "No samples database in nfcore directory"
diff --git a/babs/docs/makefile b/babs/docs/makefile
--- a/babs/docs/makefile
+++ b/babs/docs/makefile
@@ -9,21 +9,18 @@ experiment_table = $(wildcard experiment_table.csv)
 
 .PHONY: build run clean 
 
-run:  ## Empty target just to conform to general pattern
+build: run
+	echo "WARNING: 'build' is deprecated - `make run` has been invoked for you, instead. In future, there's no need to build"
 
 # Logic is to use existence of non-empty report.err as a flag for
-# problem.  On any build, put any problems in tmp.err, and at the end
+# problem.  On any run, put any problems in tmp.err, and at the end
 # we reflect anything generated into the report.err _and_ make sure
-# tmp.err is no longer present to allow future builds a clean state.
+# tmp.err is no longer present to allow future runs a clean state.
 
-# Any 'build' prerequisites that can potentially be constructed, leave
-# as literal strings rather than macros. But also have a wildcard
-# macro (e.g. 'samplesheet' above) so that the behaviour can be
-# conditional upon existence or not of a pre-written one.
 
-build: $(specfiles) samplesheet.csv $(configs) $(experiment_table) ## Basic check that the contents of the docs folder conforms to requirements
-	$(GIT) add ../.pipeline-version ../.gitignore ../makefile ../shared.mk ../readme.md shared.mk
-	$(GIT) commit -m "Add top-level pipeline files" || true
+run: $(specfiles) samplesheet.csv $(configs) $(experiment_table) ## Basic check that the contents of the docs folder conforms to requirements
+	$(GIT) add shared.mk makefile .gitignore
+	$(GIT) commit -m "Adding files generated by a docs run" || echo "No docs files needed adding"
 	[ -n "$(specfiles)" ] || echo "No *.spec files in the docs directory" | tee -a tmp.err
 	[ -n "$(configs)" ] || echo "No *.config files in the docs directory" | tee -a tmp.err
 	[ -n "$(experiment_table)" ] || echo "No experiment_table.csv in the docs directory" | tee -a tmp.err
@@ -44,11 +41,11 @@ else
 limsid=$(subst asf-,,$(subst lims-,,$(setting_Lims)))
 lab-sci=$(word 2,$(subst /projects/, ,$(dir $(setting_Path))))
 fqfiles=/nemo/stp/babs/inputs/sequencing/released/$(lab-sci)$(limsid)/primary_data/*/fastq/*_R1_001.fastq.gz
-samplesheet.csv : $(wildcard ${fqfiles})
-	if [ "$(words $(wildcard ${fqfiles}))" == "0" ] ;\
-	  then echo "Couldn't find fastq files in " ${fqfiles} | tee -a tmp.err;\
+samplesheet.csv : $(wildcard $(fqfiles))
+	if [ "$(words $(wildcard $(fqfiles)))" == "0" ] ;\
+	  then echo "Couldn't find fastq files in " $(fqfiles) | tee -a tmp.err;\
 	else echo "sample,fastq_1,fastq_2" > $@;\
-	  for r1 in ${fqfiles}; do \
+	  for r1 in $(fqfiles); do \
 	    echo -n $$(basename $$r1) | sed 's/_.*/,/' >> $@ ;\
 	    echo -n "$$r1," >> $@ ;\
 	    r2=`echo $$r1 | sed 's/_R1_/_R2_/'` ;\
@@ -57,7 +54,8 @@ samplesheet.csv : $(wildcard ${fqfiles})
 	      else echo "" >> $@ ;\
 	    fi ;\
 	  done ;\
-	fi	
+	fi
+	$(GIT) add $@
 endif
 
 
